# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16fbacd45f00926066fbd37b21aaac0a6abbfba947b67221031152ce07023041686896e7c9ac628310dd07c0feb14b9976ec1ee66a1d15936990a1e44f6816b8

test:
  secret_key_base: ff62849868d5ef6eabb66e243a5b745ed97f492f3070311ed1f16577ff432f9d6ff9cd366395ac357c7698f6f1992a525fd07628ddaa43600ea803dbf20c9336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
